Log iniciado: 2025-02-28 19:12:15
==================================================
[2025-02-28 19:12:21] Login realizado com sucesso.
[2025-02-28 19:12:21] Botão de serviço clicado.
[2025-02-28 19:12:22] Mudança para o iframe lateral realizada com sucesso.
[2025-02-28 19:12:22] Itens do menu clicados com sucesso.
[2025-02-28 19:12:23] Mudança para o iframe central realizada com sucesso.
[2025-02-28 19:12:23] Processando linha 43...
[2025-02-28 19:12:25] Texto 'BARRA DO PIRAI' inserido no campo 'inputString'.
[2025-02-28 19:12:25] Lista de sugestões carregada: 1 itens encontrados.
[2025-02-28 19:12:25] Texto da primeira sugestão: ''.
[2025-02-28 19:12:26] Sugestão '' clicada com sucesso via XPath.
[2025-02-28 19:12:26] Dropdown 'contrato_chosen' aberto com sucesso.
[2025-02-28 19:12:27] Texto '36 Meses - Manutencao Light' inserido no campo com sucesso.
[2025-02-28 19:12:27] Confirmação de que o campo contém o texto '36 Meses - Manutencao Light'.
[2025-02-28 19:12:27] Tecla Enter pressionada.
[2025-02-28 19:12:27] Dropdown 'equipe_chosen' aberto com sucesso.
[2025-02-28 19:12:28] Texto 'MT005' inserido no campo com sucesso.
[2025-02-28 19:12:28] Confirmação de que o campo contém o texto 'MT005'.
[2025-02-28 19:12:28] Tecla Enter pressionada.
[2025-02-28 19:12:28] Dropdown 'tip_srv_chosen' aberto com sucesso.
[2025-02-28 19:12:29] Texto 'EMERGENCIAL' inserido no campo com sucesso.
[2025-02-28 19:12:29] Confirmação de que o campo contém o texto 'EMERGENCIAL'.
[2025-02-28 19:12:29] Tecla Enter pressionada.
[2025-02-28 19:12:29] Dropdown 'obras_chosen' aberto com sucesso.
[2025-02-28 19:12:30] Texto '96941232' inserido no campo com sucesso.
[2025-02-28 19:12:30] Confirmação de que o campo contém o texto '96941232'.
[2025-02-28 19:12:30] Tecla Enter pressionada.
[2025-02-28 19:12:30] Dropdown 'cod_irr_chosen' aberto com sucesso.
[2025-02-28 19:12:31] Texto '801' inserido no campo com sucesso.
[2025-02-28 19:12:31] Confirmação de que o campo contém o texto '801'.
[2025-02-28 19:12:31] Tecla Enter pressionada.
[2025-02-28 19:12:32] Campo 'dat_srv' preenchido com valor '10/02/2025'.
[2025-02-28 19:12:32] Campo 'hr_inic' preenchido com valor '08:00'.
[2025-02-28 19:12:32] Campo 'dat_srv2' preenchido com valor '10/02/2025'.
[2025-02-28 19:12:32] Campo 'hr_fim' preenchido com valor '17:00'.
[2025-02-28 19:12:32] Cabeçalho preenchido com sucesso.
[2025-02-28 19:12:32] Formulário salvo com sucesso.
[2025-02-28 19:12:32] Tentando acessar o iframe secundário...
[2025-02-28 19:12:33] Iframe secundário já está ativo.
[2025-02-28 19:12:34] Mudança para o iframe lateral realizada com sucesso.
[2025-02-28 19:12:34] Novo cabeçalho processado na linha 43.
[2025-02-28 19:12:34] Dropdown 'serv_chosen' aberto com sucesso.
[2025-02-28 19:12:35] Texto '3009723' inserido no campo com sucesso.
[2025-02-28 19:12:35] Confirmação de que o campo contém o texto '3009723'.
[2025-02-28 19:12:35] Tecla Enter pressionada.
[2025-02-28 19:12:36] Campo 'qtd' preenchido com valor '150.00'.
[2025-02-28 19:12:38] Botão 'Incluir' clicado com sucesso.
[2025-02-28 19:12:38] Linha 43 processada com sucesso.
[2025-02-28 19:12:38] Planilha salva mantendo a formatação de data/hora.
[2025-02-28 19:12:38] Planilha salva com status atualizado.
[2025-02-28 19:12:38] Processando linha 44...
[2025-02-28 19:12:39] Dropdown 'serv_chosen' aberto com sucesso.
[2025-02-28 19:12:40] Texto '3006290' inserido no campo com sucesso.
[2025-02-28 19:12:40] Confirmação de que o campo contém o texto '3006290'.
[2025-02-28 19:12:40] Tecla Enter pressionada.
[2025-02-28 19:12:40] Campo 'qtd' preenchido com valor '1.00'.
[2025-02-28 19:12:41] Botão 'Incluir' clicado com sucesso.
[2025-02-28 19:12:41] Linha 44 processada com sucesso.
[2025-02-28 19:12:41] Planilha salva mantendo a formatação de data/hora.
[2025-02-28 19:12:41] Planilha salva com status atualizado.
[2025-02-28 19:12:41] Processando linha 45...
[2025-02-28 19:12:42] Dropdown 'serv_chosen' aberto com sucesso.
[2025-02-28 19:13:02] Erro ao inserir e confirmar o texto '3006291': Timeout ao aguardar o campo ou o texto.
[2025-02-28 19:13:03] Campo 'qtd' preenchido com valor '1.00'.
[2025-02-28 19:13:03] Botão 'Incluir' clicado com sucesso.
[2025-02-28 19:13:03] Linha 45 processada com sucesso.
[2025-02-28 19:13:04] Planilha salva mantendo a formatação de data/hora.
[2025-02-28 19:13:04] Planilha salva com status atualizado.
[2025-02-28 19:13:04] Processando linha 46...
[2025-02-28 19:13:05] Erro ao preencher serv_chosen: 3011154: Message: element click intercepted: Element <div class="chosen-container chosen-container-single" style="width: 400px;" title="" id="serv_chosen">...</div> is not clickable at point (339, 25). Other element would receive the click: <div aria-labelledby="swal2-title" aria-describedby="swal2-html-container" class="swal2-popup swal2-toast colored-toast swal2-icon-warning swal2-show" tabindex="-1" role="alert" aria-live="polite" style="width: 100%; display: grid;">...</div>
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF65F806F15+28773]
	(No symbol) [0x00007FF65F772600]
	(No symbol) [0x00007FF65F608FAA]
	(No symbol) [0x00007FF65F667109]
	(No symbol) [0x00007FF65F664AD2]
	(No symbol) [0x00007FF65F661B81]
	(No symbol) [0x00007FF65F660A91]
	(No symbol) [0x00007FF65F652284]
	(No symbol) [0x00007FF65F68724A]
	(No symbol) [0x00007FF65F651B36]
	(No symbol) [0x00007FF65F687460]
	(No symbol) [0x00007FF65F6AF6F3]
	(No symbol) [0x00007FF65F687023]
	(No symbol) [0x00007FF65F64FF5E]
	(No symbol) [0x00007FF65F6511E3]
	GetHandleVerifier [0x00007FF65FB5425D+3490733]
	GetHandleVerifier [0x00007FF65FB6BA43+3586963]
	GetHandleVerifier [0x00007FF65FB6147D+3544525]
	GetHandleVerifier [0x00007FF65F8CC9DA+838442]
	(No symbol) [0x00007FF65F77D04F]
	(No symbol) [0x00007FF65F779614]
	(No symbol) [0x00007FF65F7797B6]
	(No symbol) [0x00007FF65F768CE9]
	BaseThreadInitThunk [0x00007FFDEF877374+20]
	RtlUserThreadStart [0x00007FFDF021CC91+33]

[2025-02-28 19:13:05] Campo 'qtd' preenchido com valor '1.00'.
[2025-02-28 19:13:06] Erro ao preencher os dados 1.00: Message: element click intercepted: Element <input type="submit" class="dt-button btn_green" name="submit" value="Incluir" title="Incluir registro" onclick="botao=this.value"> is not clickable at point (656, 23). Other element would receive the click: <div aria-labelledby="swal2-title" aria-describedby="swal2-html-container" class="swal2-popup swal2-toast colored-toast swal2-icon-warning swal2-show" tabindex="-1" role="alert" aria-live="polite" style="width: 100%; display: grid;">...</div>
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF65F806F15+28773]
	(No symbol) [0x00007FF65F772600]
	(No symbol) [0x00007FF65F608FAA]
	(No symbol) [0x00007FF65F667109]
	(No symbol) [0x00007FF65F664AD2]
	(No symbol) [0x00007FF65F661B81]
	(No symbol) [0x00007FF65F660A91]
	(No symbol) [0x00007FF65F652284]
	(No symbol) [0x00007FF65F68724A]
	(No symbol) [0x00007FF65F651B36]
	(No symbol) [0x00007FF65F687460]
	(No symbol) [0x00007FF65F6AF6F3]
	(No symbol) [0x00007FF65F687023]
	(No symbol) [0x00007FF65F64FF5E]
	(No symbol) [0x00007FF65F6511E3]
	GetHandleVerifier [0x00007FF65FB5425D+3490733]
	GetHandleVerifier [0x00007FF65FB6BA43+3586963]
	GetHandleVerifier [0x00007FF65FB6147D+3544525]
	GetHandleVerifier [0x00007FF65F8CC9DA+838442]
	(No symbol) [0x00007FF65F77D04F]
	(No symbol) [0x00007FF65F779614]
	(No symbol) [0x00007FF65F7797B6]
	(No symbol) [0x00007FF65F768CE9]
	BaseThreadInitThunk [0x00007FFDEF877374+20]
	RtlUserThreadStart [0x00007FFDF021CC91+33]

[2025-02-28 19:13:06] Mudança para o iframe central realizada com sucesso.
[2025-02-28 19:13:07] Botão 'Cancelar' clicado com sucesso.
[2025-02-28 19:13:08] Alerta e concluido aceito automaticamente.
[2025-02-28 19:13:10] WebDriver finalizado com sucesso.
[2025-02-28 19:13:10] Linha 46 processada com sucesso.
[2025-02-28 19:13:11] Planilha salva mantendo a formatação de data/hora.
[2025-02-28 19:13:11] Planilha salva com status atualizado.
[2025-02-28 19:13:11] Processando linha 47...
[2025-02-28 19:13:27] Erro ao preencher serv_chosen: 3006969: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0DF890>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:13:43] Erro ao preencher os dados 6.00: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0DEE70>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:14:00] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEDB5F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:14:16] Erro ao cancelar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0DF6B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:14:16] Linha 47 processada com sucesso.
[2025-02-28 19:14:16] Erro ao salvar planilha mantendo a formatação: [Errno 13] Permission denied: 'dados_apontamento_teste.xlsx'
[2025-02-28 19:14:16] Planilha salva com status atualizado.
[2025-02-28 19:14:16] Processando linha 48...
[2025-02-28 19:14:33] Erro ao preencher serv_chosen: 3006938: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF44BC0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:14:49] Erro ao preencher os dados 70.00: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483CB0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:15:05] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF45C70>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:15:21] Erro ao cancelar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF47020>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:15:21] Linha 48 processada com sucesso.
[2025-02-28 19:15:22] Erro ao salvar planilha mantendo a formatação: [Errno 13] Permission denied: 'dados_apontamento_teste.xlsx'
[2025-02-28 19:15:22] Planilha salva com status atualizado.
[2025-02-28 19:15:22] Processando linha 49...
[2025-02-28 19:15:38] Erro ao preencher serv_chosen: 3006974: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB1C10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:15:54] Erro ao preencher os dados 1.00: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3500>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:16:11] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2570>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:16:27] Erro ao cancelar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2A80>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:16:27] Linha 49 processada com sucesso.
[2025-02-28 19:16:27] Erro ao salvar planilha mantendo a formatação: [Errno 13] Permission denied: 'dados_apontamento_teste.xlsx'
[2025-02-28 19:16:27] Planilha salva com status atualizado.
[2025-02-28 19:16:27] Processando linha 50...
[2025-02-28 19:16:43] Erro ao preencher serv_chosen: 3006950: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB95AB70>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:17:00] Erro ao preencher os dados 1.00: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB958BC0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:17:16] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB95BCB0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:17:32] Erro ao cancelar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB958380>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:17:32] Linha 50 processada com sucesso.
[2025-02-28 19:17:33] Planilha salva mantendo a formatação de data/hora.
[2025-02-28 19:17:33] Planilha salva com status atualizado.
[2025-02-28 19:17:33] Processando linha 51...
[2025-02-28 19:17:33] Ciclo: 51 para o cabeçalho anterior 50.
[2025-02-28 19:17:49] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFE00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:18:05] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC4817F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:18:05] Ciclo finalizado para o cabeçalho anterior na linha 51.
[2025-02-28 19:18:22] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8890>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:18:39] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC481C10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:18:55] Erro ao preencher o cabeçalho na linha 51: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480830>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:18:55] Processando linha 52...
[2025-02-28 19:18:55] Ciclo: 52 para o cabeçalho anterior 51.
[2025-02-28 19:19:11] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B101D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:19:28] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4A40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:19:28] Ciclo finalizado para o cabeçalho anterior na linha 52.
[2025-02-28 19:19:44] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE6360>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:20:01] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFE30>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:20:17] Erro ao preencher o cabeçalho na linha 52: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC4817C0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:20:17] Processando linha 53...
[2025-02-28 19:20:17] Ciclo: 53 para o cabeçalho anterior 52.
[2025-02-28 19:20:33] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2540>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:20:50] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480860>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:20:50] Ciclo finalizado para o cabeçalho anterior na linha 53.
[2025-02-28 19:21:06] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFE00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:21:23] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E41D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:21:39] Erro ao preencher o cabeçalho na linha 53: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2510>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:21:39] Processando linha 54...
[2025-02-28 19:21:39] Ciclo: 54 para o cabeçalho anterior 53.
[2025-02-28 19:21:56] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EF7A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:22:12] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480BC0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:22:12] Ciclo finalizado para o cabeçalho anterior na linha 54.
[2025-02-28 19:22:28] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB1EE0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:22:45] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A2A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:23:01] Erro ao preencher o cabeçalho na linha 54: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC481880>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:23:01] Processando linha 55...
[2025-02-28 19:23:01] Ciclo: 55 para o cabeçalho anterior 54.
[2025-02-28 19:23:18] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFB90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:23:34] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289A00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:23:34] Ciclo finalizado para o cabeçalho anterior na linha 55.
[2025-02-28 19:23:50] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E78F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:24:07] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFF80>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:24:23] Erro ao preencher o cabeçalho na linha 55: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480BF0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:24:23] Processando linha 56...
[2025-02-28 19:24:23] Ciclo: 56 para o cabeçalho anterior 55.
[2025-02-28 19:24:40] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A2A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:24:56] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2D50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:24:56] Ciclo finalizado para o cabeçalho anterior na linha 56.
[2025-02-28 19:25:12] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483B90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:25:29] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB49E6F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:25:45] Erro ao preencher o cabeçalho na linha 56: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288980>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:25:45] Processando linha 57...
[2025-02-28 19:25:45] Ciclo: 57 para o cabeçalho anterior 56.
[2025-02-28 19:26:02] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB49E630>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:26:18] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480BC0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:26:18] Ciclo finalizado para o cabeçalho anterior na linha 57.
[2025-02-28 19:26:34] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2900>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:26:52] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289CA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:27:09] Erro ao preencher o cabeçalho na linha 57: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4DE80>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:27:09] Processando linha 58...
[2025-02-28 19:27:09] Ciclo: 58 para o cabeçalho anterior 57.
[2025-02-28 19:27:25] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E41D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:27:41] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE7AA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:27:41] Ciclo finalizado para o cabeçalho anterior na linha 58.
[2025-02-28 19:27:58] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB2B0440>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:28:15] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFD40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:28:31] Erro ao preencher o cabeçalho na linha 58: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE5B20>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:28:31] Processando linha 59...
[2025-02-28 19:28:31] Ciclo: 59 para o cabeçalho anterior 58.
[2025-02-28 19:28:47] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3950>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:29:04] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC481010>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:29:04] Ciclo finalizado para o cabeçalho anterior na linha 59.
[2025-02-28 19:29:20] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4D340>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:29:37] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E7D10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:29:53] Erro ao preencher o cabeçalho na linha 59: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EDB50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:29:53] Processando linha 60...
[2025-02-28 19:29:53] Ciclo: 60 para o cabeçalho anterior 59.
[2025-02-28 19:30:10] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC481B50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:30:26] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EC260>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:30:26] Ciclo finalizado para o cabeçalho anterior na linha 60.
[2025-02-28 19:30:42] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4920>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:30:59] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2C00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:31:16] Erro ao preencher o cabeçalho na linha 60: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B10140>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:31:16] Processando linha 61...
[2025-02-28 19:31:16] Ciclo: 61 para o cabeçalho anterior 60.
[2025-02-28 19:31:32] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB27B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:31:48] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE5CD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:31:48] Ciclo finalizado para o cabeçalho anterior na linha 61.
[2025-02-28 19:32:05] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFB90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:32:21] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480860>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:32:38] Erro ao preencher o cabeçalho na linha 61: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE77D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:32:38] Processando linha 62...
[2025-02-28 19:32:38] Ciclo: 62 para o cabeçalho anterior 61.
[2025-02-28 19:32:54] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3950>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:33:11] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE4A10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:33:11] Ciclo finalizado para o cabeçalho anterior na linha 62.
[2025-02-28 19:33:27] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289AF0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:33:44] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4E930>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:34:00] Erro ao preencher o cabeçalho na linha 62: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E41D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:34:00] Processando linha 63...
[2025-02-28 19:34:00] Ciclo: 63 para o cabeçalho anterior 62.
[2025-02-28 19:34:16] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFBF0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:34:33] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFC20>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:34:33] Ciclo finalizado para o cabeçalho anterior na linha 63.
[2025-02-28 19:34:49] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB49E690>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:35:06] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4E930>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:35:22] Erro ao preencher o cabeçalho na linha 63: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A720>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:35:22] Processando linha 64...
[2025-02-28 19:35:22] Ciclo: 64 para o cabeçalho anterior 63.
[2025-02-28 19:35:39] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE4A10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:35:55] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2420>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:35:55] Ciclo finalizado para o cabeçalho anterior na linha 64.
[2025-02-28 19:36:11] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4590>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:36:28] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289BB0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:36:45] Erro ao preencher o cabeçalho na linha 64: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EF860>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:36:45] Processando linha 65...
[2025-02-28 19:36:45] Ciclo: 65 para o cabeçalho anterior 64.
[2025-02-28 19:37:01] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3BF0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:37:17] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7DE50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:37:17] Ciclo finalizado para o cabeçalho anterior na linha 65.
[2025-02-28 19:37:34] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A930>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:37:51] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B10050>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:38:07] Erro ao preencher o cabeçalho na linha 65: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3950>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:38:07] Processando linha 66...
[2025-02-28 19:38:07] Ciclo: 66 para o cabeçalho anterior 65.
[2025-02-28 19:38:23] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EC770>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:38:40] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A030>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:38:40] Ciclo finalizado para o cabeçalho anterior na linha 66.
[2025-02-28 19:38:56] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE44A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:39:13] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3950>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:39:29] Erro ao preencher o cabeçalho na linha 66: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE56D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:39:29] Processando linha 67...
[2025-02-28 19:39:29] Ciclo: 67 para o cabeçalho anterior 66.
[2025-02-28 19:39:45] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289640>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:40:02] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8410>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:40:02] Ciclo finalizado para o cabeçalho anterior na linha 67.
[2025-02-28 19:40:18] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4FE0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:40:35] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B10170>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:40:51] Erro ao preencher o cabeçalho na linha 67: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E4380>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:40:51] Processando linha 68...
[2025-02-28 19:40:51] Ciclo: 68 para o cabeçalho anterior 67.
[2025-02-28 19:41:08] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7C1D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:41:24] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB1F40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:41:24] Ciclo finalizado para o cabeçalho anterior na linha 68.
[2025-02-28 19:41:40] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE44A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:41:57] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A99DC3B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:42:14] Erro ao preencher o cabeçalho na linha 68: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8AA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:42:14] Processando linha 69...
[2025-02-28 19:42:14] Ciclo: 69 para o cabeçalho anterior 68.
[2025-02-28 19:42:30] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3290>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:42:46] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE73B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:42:46] Ciclo finalizado para o cabeçalho anterior na linha 69.
[2025-02-28 19:43:03] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EF830>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:43:20] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB49CB00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:43:36] Erro ao preencher o cabeçalho na linha 69: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3BF0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:43:36] Processando linha 70...
[2025-02-28 19:43:36] Ciclo: 70 para o cabeçalho anterior 69.
[2025-02-28 19:43:52] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE5C10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:44:09] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC4827B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:44:09] Ciclo finalizado para o cabeçalho anterior na linha 70.
[2025-02-28 19:44:25] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F9BB0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:44:42] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3F20>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:44:58] Erro ao preencher o cabeçalho na linha 70: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE68D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:44:58] Processando linha 71...
[2025-02-28 19:44:58] Ciclo: 71 para o cabeçalho anterior 70.
[2025-02-28 19:45:15] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483AD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:45:31] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2270>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:45:31] Ciclo finalizado para o cabeçalho anterior na linha 71.
[2025-02-28 19:45:47] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE43E0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:46:04] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480BC0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:46:20] Erro ao preencher o cabeçalho na linha 71: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4D340>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:46:20] Processando linha 72...
[2025-02-28 19:46:20] Ciclo: 72 para o cabeçalho anterior 71.
[2025-02-28 19:46:37] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE7800>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:46:53] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB1A00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:46:53] Ciclo finalizado para o cabeçalho anterior na linha 72.
[2025-02-28 19:47:09] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28B500>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:47:26] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC2884D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:47:43] Erro ao preencher o cabeçalho na linha 72: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3560>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:47:43] Processando linha 73...
[2025-02-28 19:47:43] Ciclo: 73 para o cabeçalho anterior 72.
[2025-02-28 19:47:59] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE7350>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:48:15] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288260>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:48:15] Ciclo finalizado para o cabeçalho anterior na linha 73.
[2025-02-28 19:48:32] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A99DC3B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:48:49] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE6A50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:49:05] Erro ao preencher o cabeçalho na linha 73: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB1F40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:49:05] Processando linha 74...
[2025-02-28 19:49:05] Ciclo: 74 para o cabeçalho anterior 73.
[2025-02-28 19:49:21] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288530>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:49:38] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE7EF0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:49:38] Ciclo finalizado para o cabeçalho anterior na linha 74.
[2025-02-28 19:49:54] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE75F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:50:11] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FB500>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:50:27] Erro ao preencher o cabeçalho na linha 74: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28B620>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:50:27] Processando linha 75...
[2025-02-28 19:50:27] Ciclo: 75 para o cabeçalho anterior 74.
[2025-02-28 19:50:44] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FBCE0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:51:00] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE7770>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:51:00] Ciclo finalizado para o cabeçalho anterior na linha 75.
[2025-02-28 19:51:16] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE7E30>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:51:33] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28AAE0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:51:50] Erro ao preencher o cabeçalho na linha 75: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B10140>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:51:50] Processando linha 76...
[2025-02-28 19:51:50] Ciclo: 76 para o cabeçalho anterior 75.
[2025-02-28 19:52:06] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4F20>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:52:22] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7C110>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:52:22] Ciclo finalizado para o cabeçalho anterior na linha 76.
[2025-02-28 19:52:39] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288B00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:52:56] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4ED50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:53:12] Erro ao preencher o cabeçalho na linha 76: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB3BF0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:53:12] Processando linha 77...
[2025-02-28 19:53:12] Ciclo: 77 para o cabeçalho anterior 76.
[2025-02-28 19:53:28] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483E00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:53:45] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8410>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:53:45] Ciclo finalizado para o cabeçalho anterior na linha 77.
[2025-02-28 19:54:01] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC4826F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:54:18] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC4813A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:54:34] Erro ao preencher o cabeçalho na linha 77: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB0470>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:54:34] Processando linha 78...
[2025-02-28 19:54:34] Ciclo: 78 para o cabeçalho anterior 77.
[2025-02-28 19:54:51] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE7AA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:55:07] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4FE60>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:55:07] Ciclo finalizado para o cabeçalho anterior na linha 78.
[2025-02-28 19:55:23] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7C380>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:55:40] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC4832C0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:55:57] Erro ao preencher o cabeçalho na linha 78: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4950>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:55:57] Processando linha 79...
[2025-02-28 19:55:57] Ciclo: 79 para o cabeçalho anterior 78.
[2025-02-28 19:56:13] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FA060>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:56:29] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC482600>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:56:29] Ciclo finalizado para o cabeçalho anterior na linha 79.
[2025-02-28 19:56:46] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB1640>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:57:03] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B10080>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:57:19] Erro ao preencher o cabeçalho na linha 79: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4C4D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:57:19] Processando linha 80...
[2025-02-28 19:57:19] Ciclo: 80 para o cabeçalho anterior 79.
[2025-02-28 19:57:35] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480D40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:57:52] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483A10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:57:52] Ciclo finalizado para o cabeçalho anterior na linha 80.
[2025-02-28 19:58:08] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE7A10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:58:25] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FB860>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:58:41] Erro ao preencher o cabeçalho na linha 80: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC481880>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:58:41] Processando linha 81...
[2025-02-28 19:58:41] Ciclo: 81 para o cabeçalho anterior 80.
[2025-02-28 19:58:58] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB0B30>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 19:59:14] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EC6B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:59:14] Ciclo finalizado para o cabeçalho anterior na linha 81.
[2025-02-28 19:59:30] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB49E6F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 19:59:47] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483DA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:00:04] Erro ao preencher o cabeçalho na linha 81: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F9910>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:00:04] Processando linha 82...
[2025-02-28 20:00:04] Ciclo: 82 para o cabeçalho anterior 81.
[2025-02-28 20:00:20] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFE30>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:00:36] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC4826F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:00:36] Ciclo finalizado para o cabeçalho anterior na linha 82.
[2025-02-28 20:00:53] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB0E90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:01:10] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFB90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:01:26] Erro ao preencher o cabeçalho na linha 82: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289790>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:01:26] Processando linha 83...
[2025-02-28 20:01:26] Ciclo: 83 para o cabeçalho anterior 82.
[2025-02-28 20:01:42] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2ED0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:01:58] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483E00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:01:58] Ciclo finalizado para o cabeçalho anterior na linha 83.
[2025-02-28 20:02:15] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288B00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:02:32] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289220>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:02:48] Erro ao preencher o cabeçalho na linha 83: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483AD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:02:48] Processando linha 84...
[2025-02-28 20:02:48] Ciclo: 84 para o cabeçalho anterior 83.
[2025-02-28 20:03:04] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB49CB00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:03:21] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28BE00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:03:21] Ciclo finalizado para o cabeçalho anterior na linha 84.
[2025-02-28 20:03:37] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FB860>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:03:54] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB1EE0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:04:10] Erro ao preencher o cabeçalho na linha 84: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483170>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:04:10] Processando linha 85...
[2025-02-28 20:04:10] Ciclo: 85 para o cabeçalho anterior 84.
[2025-02-28 20:04:26] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A4E0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:04:43] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483110>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:04:43] Ciclo finalizado para o cabeçalho anterior na linha 85.
[2025-02-28 20:04:59] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7E300>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:05:16] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4F4D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:05:32] Erro ao preencher o cabeçalho na linha 85: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288A10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:05:32] Processando linha 86...
[2025-02-28 20:05:32] Ciclo: 86 para o cabeçalho anterior 85.
[2025-02-28 20:05:49] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFAD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:06:05] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE4A10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:06:05] Ciclo finalizado para o cabeçalho anterior na linha 86.
[2025-02-28 20:06:21] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4290>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:06:38] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC481880>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:06:55] Erro ao preencher o cabeçalho na linha 86: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4B90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:06:55] Processando linha 87...
[2025-02-28 20:06:55] Ciclo: 87 para o cabeçalho anterior 86.
[2025-02-28 20:07:11] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE4950>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:07:27] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EF7A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:07:27] Ciclo finalizado para o cabeçalho anterior na linha 87.
[2025-02-28 20:07:44] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC481B50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:08:01] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483E00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:08:17] Erro ao preencher o cabeçalho na linha 87: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFDD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:08:17] Processando linha 88...
[2025-02-28 20:08:17] Ciclo: 88 para o cabeçalho anterior 87.
[2025-02-28 20:08:33] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E7380>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:08:50] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8410>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:08:50] Ciclo finalizado para o cabeçalho anterior na linha 88.
[2025-02-28 20:09:06] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE48F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:09:23] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE7A10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:09:39] Erro ao preencher o cabeçalho na linha 88: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFB90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:09:39] Processando linha 89...
[2025-02-28 20:09:39] Ciclo: 89 para o cabeçalho anterior 88.
[2025-02-28 20:09:55] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7EF90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:10:12] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480D40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:10:12] Ciclo finalizado para o cabeçalho anterior na linha 89.
[2025-02-28 20:10:28] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFDD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:10:45] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E7DA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:11:01] Erro ao preencher o cabeçalho na linha 89: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE7800>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:11:01] Processando linha 90...
[2025-02-28 20:11:01] Ciclo: 90 para o cabeçalho anterior 89.
[2025-02-28 20:11:18] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4590>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:11:34] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B10140>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:11:34] Ciclo finalizado para o cabeçalho anterior na linha 90.
[2025-02-28 20:11:50] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483A40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:12:07] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8410>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:12:24] Erro ao preencher o cabeçalho na linha 90: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC480D40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:12:24] Processando linha 91...
[2025-02-28 20:12:24] Ciclo: 91 para o cabeçalho anterior 90.
[2025-02-28 20:12:40] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFB90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:12:56] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E7020>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:12:56] Ciclo finalizado para o cabeçalho anterior na linha 91.
[2025-02-28 20:13:13] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB2540>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:13:29] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE7350>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:13:46] Erro ao preencher o cabeçalho na linha 91: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B10140>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:13:46] Processando linha 92...
[2025-02-28 20:13:46] Ciclo: 92 para o cabeçalho anterior 91.
[2025-02-28 20:14:02] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483B60>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:14:19] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289280>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:14:19] Ciclo finalizado para o cabeçalho anterior na linha 92.
[2025-02-28 20:14:35] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8890>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:14:52] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EF860>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:15:08] Erro ao preencher o cabeçalho na linha 92: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E4140>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:15:08] Processando linha 93...
[2025-02-28 20:15:08] Ciclo: 93 para o cabeçalho anterior 92.
[2025-02-28 20:15:25] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289220>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:15:41] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EC5C0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:15:41] Ciclo finalizado para o cabeçalho anterior na linha 93.
[2025-02-28 20:15:57] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC482600>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:16:14] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A180>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:16:30] Erro ao preencher o cabeçalho na linha 93: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A870>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:16:30] Processando linha 94...
[2025-02-28 20:16:30] Ciclo: 94 para o cabeçalho anterior 93.
[2025-02-28 20:16:47] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483B60>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:17:03] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EC7A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:17:03] Ciclo finalizado para o cabeçalho anterior na linha 94.
[2025-02-28 20:17:19] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288F80>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:17:36] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC289C70>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:17:53] Erro ao preencher o cabeçalho na linha 94: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EC7A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:17:53] Processando linha 95...
[2025-02-28 20:17:53] Ciclo: 95 para o cabeçalho anterior 94.
[2025-02-28 20:18:09] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FAB70>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:18:26] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A570>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:18:26] Ciclo finalizado para o cabeçalho anterior na linha 95.
[2025-02-28 20:18:42] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A99DC3B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:18:59] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4C9E0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:19:15] Erro ao preencher o cabeçalho na linha 95: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFE30>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:19:15] Processando linha 96...
[2025-02-28 20:19:15] Ciclo: 96 para o cabeçalho anterior 95.
[2025-02-28 20:19:31] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8890>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:19:48] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F81D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:19:48] Ciclo finalizado para o cabeçalho anterior na linha 96.
[2025-02-28 20:20:04] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EF7A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:20:21] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4DE80>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:20:37] Erro ao preencher o cabeçalho na linha 96: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE73B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:20:37] Processando linha 97...
[2025-02-28 20:20:37] Ciclo: 97 para o cabeçalho anterior 96.
[2025-02-28 20:20:54] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE56D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:21:10] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4D010>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:21:10] Ciclo finalizado para o cabeçalho anterior na linha 97.
[2025-02-28 20:21:26] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EDB50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:21:43] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FB410>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:22:00] Erro ao preencher o cabeçalho na linha 97: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F9910>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:22:00] Processando linha 98...
[2025-02-28 20:22:00] Ciclo: 98 para o cabeçalho anterior 97.
[2025-02-28 20:22:16] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7DE50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:22:32] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E7380>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:22:32] Ciclo finalizado para o cabeçalho anterior na linha 98.
[2025-02-28 20:22:49] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE4FE0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:23:06] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE7FB0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:23:22] Erro ao preencher o cabeçalho na linha 98: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4FE60>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:23:22] Processando linha 99...
[2025-02-28 20:23:22] Ciclo: 99 para o cabeçalho anterior 98.
[2025-02-28 20:23:38] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFBF0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:23:55] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC4834D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:23:55] Ciclo finalizado para o cabeçalho anterior na linha 99.
[2025-02-28 20:24:11] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FABD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:24:28] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFC20>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:24:44] Erro ao preencher o cabeçalho na linha 99: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E7F50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:24:44] Processando linha 100...
[2025-02-28 20:24:44] Ciclo: 100 para o cabeçalho anterior 99.
[2025-02-28 20:25:01] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A180>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:25:17] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE7E30>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:25:17] Ciclo finalizado para o cabeçalho anterior na linha 100.
[2025-02-28 20:25:33] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4E390>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:25:50] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EF7A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:26:07] Erro ao preencher o cabeçalho na linha 100: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28B1D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:26:07] Processando linha 101...
[2025-02-28 20:26:07] Ciclo: 101 para o cabeçalho anterior 100.
[2025-02-28 20:26:23] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F8AA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:26:39] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7EBD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:26:39] Ciclo finalizado para o cabeçalho anterior na linha 101.
[2025-02-28 20:26:56] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5A9B10170>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:27:13] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC28A540>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:27:29] Erro ao preencher o cabeçalho na linha 101: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE46E0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:27:29] Processando linha 102...
[2025-02-28 20:27:29] Ciclo: 102 para o cabeçalho anterior 101.
[2025-02-28 20:27:45] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7EBD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:28:02] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0F9670>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:28:02] Ciclo finalizado para o cabeçalho anterior na linha 102.
[2025-02-28 20:28:18] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288980>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:28:35] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FBD10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:28:51] Erro ao preencher o cabeçalho na linha 102: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7C1D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:28:51] Processando linha 103...
[2025-02-28 20:28:51] Ciclo: 103 para o cabeçalho anterior 102.
[2025-02-28 20:29:08] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABFE6360>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:29:24] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288C20>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:29:24] Ciclo finalizado para o cabeçalho anterior na linha 103.
[2025-02-28 20:29:41] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E5190>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:29:57] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7E300>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:30:14] Erro ao preencher o cabeçalho na linha 103: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC0FA150>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:30:14] Processando linha 104...
[2025-02-28 20:30:14] Ciclo: 104 para o cabeçalho anterior 103.
[2025-02-28 20:30:30] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC288F50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:30:47] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AB8EFCE0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:30:47] Ciclo finalizado para o cabeçalho anterior na linha 104.
[2025-02-28 20:31:03] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4F740>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:31:20] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEB1370>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:31:36] Erro ao preencher o cabeçalho na linha 104: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC2885F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:31:36] Processando linha 105...
[2025-02-28 20:31:36] Ciclo: 105 para o cabeçalho anterior 104.
[2025-02-28 20:31:53] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4C0E0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:32:09] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC482C00>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:32:09] Ciclo finalizado para o cabeçalho anterior na linha 105.
[2025-02-28 20:32:25] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABEE44A0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:32:42] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E69F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:32:58] Erro ao preencher o cabeçalho na linha 105: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483C50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:32:58] Processando linha 106...
[2025-02-28 20:32:58] Ciclo: 106 para o cabeçalho anterior 105.
[2025-02-28 20:33:15] Mudança para o iframe central erro: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/frame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4E930>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')).
[2025-02-28 20:33:31] Erro ao finalizar: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC3E7D10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:33:31] Ciclo finalizado para o cabeçalho anterior na linha 106.
[2025-02-28 20:33:47] Erro inesperado ao processar a sugestão: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABE7D250>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:34:04] Erro ao preencher o cabeçalho: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5ABF4F4D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:34:21] Erro ao preencher o cabeçalho na linha 106: HTTPConnectionPool(host='localhost', port=58690): Max retries exceeded with url: /session/f886090b5503b30f23d875f7c37f5dad/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5AC483A40>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
[2025-02-28 20:34:21] Processando linha 107...
[2025-02-28 20:34:21] Ciclo: 107 para o cabeçalho anterior 106.
